plugins = []
headers = []
redirects = []

[build]
edge_functions = "C:\\Users\\emupa\\LegalPath\\netlify\\edge-functions"
publish = "C:\\Users\\emupa\\LegalPath"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[edge_functions]]
function = "auth"
path = "/*"

[functions]

[functions."*"]